# Generated by Django 5.1.3 on 2025-04-15 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_habit_habitrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='HabitRecord',
        ),
    ]
