# Generated by Django 5.1.3 on 2025-05-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_entry_owner_alter_habit_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitlog',
            name='habit',
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.DeleteModel(
            name='HabitLog',
        ),
    ]
