# Generated by Django 5.1.3 on 2025-04-30 03:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_alter_entry_owner_alter_topic_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('owner', 'name')},
        ),
    ]
