# Generated by Django 5.1.3 on 2025-04-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_alter_habit_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together=set(),
        ),
    ]
