# Generated by Django 5.1.3 on 2025-05-03 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0013_alter_habit_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcheckin',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='learning_logs.habit'),
        ),
    ]
